
[mitm]
hostname = *.baidu.com,*.baidubce.com,*.bdstatic.com,*.baiducontent.com
# 只解密百度系，其他不过MITM

[rewrite_local]
# 电信百度免流固定头
^https?://.*\.(baidu|baidubce|bdstatic|baiducontent)\.com request-header-add Host 153.3.236.22:443
^https?://.*\.(baidu|baidubce|bdstatic|baiducontent)\.com request-header-add X-T5-Auth 683556433
^https?://.*\.(baidu|baidubce|bdstatic|baiducontent)\.com request-header-add Connection Keep-Alive
^https?://.*\.(baidu|baidubce|bdstatic|baiducontent)\.com request-header-add User-Agent okhttp/3.11.0 Dalvik/2.1.0 (Linux; U; Android 11; Redmi K30 5G Build/RKQ1.200826.002) baiduboxapp/11.0.5.12 (Baidu; P1 11)

[filter_local]
# 百度走代理（你自己在QX里选一个电信节点，比如北京电信）
host-suffix,baidu.com,PROXY
host-suffix,baidubce.com,PROXY
host-suffix,bdstatic.com,PROXY
host-suffix,baiducontent.com,PROXY
# 其他全部直连
final,direct
