[server_local]
http=220.181.33.174:443, tag=北京电信
http=220.181.7.1:443, tag=北京电信1
http=220.181.111.189:443, tag=北京电信2
http=180.101.50.249:443, tag=南京电信
http=180.101.50.208:443, tag=南京电信1
http=14.215.182.75:443, tag=广州电信

[mitm]
hostname = *.baidu.com,*.baidubce.com,*.bdstatic.com,*.baiducontent.com

[rewrite_local]
^https?://.*\.(baidu|baidubce|bdstatic|baiducontent)\.com request-header-add Host 153.3.236.22:443
^https?://.*\.(baidu|baidubce|bdstatic|baiducontent)\.com request-header-add X-T5-Auth 683556433
^https?://.*\.(baidu|baidubce|bdstatic|baiducontent)\.com request-header-add Connection Keep-Alive
^https?://.*\.(baidu|baidubce|bdstatic|baiducontent)\.com request-header-add User-Agent okhttp/3.11.0 Dalvik/2.1.0 (Linux; U; Android 11; Redmi K30 5G Build/RKQ1.200826.002) baiduboxapp/11.0.5.12 (Baidu; P1 11)

[filter_local]
host-suffix,baidu.com,北京电信
host-suffix,baidubce.com,北京电信
host-suffix,bdstatic.com,北京电信
host-suffix,baiducontent.com,北京电信
final,direct
