
#!author=fmz200
#!name=X(Twitter)网页版功能增强
#!date 2026-06-01 23:30:00

^https?:\/\/x\.com\/i\/api\/graphql\/[^\/]+\/PinnedTimelines\? url script-response-body https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/X/XWebEnhance.js

hostname = x.com
